author = "Themefisher"
description = "This is meta description"
[banner]
heading = "The New UMoMA Opens its Doors"
image = "images/2020-landscape-1-2.png"
[blog]
heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."
[call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Contact us for more information."
[footer]
address = "123 Main Street <br> New York, NY 10001"
content = "This may be a good place to introduce yourself and your site or include some credits."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About This Site"
[gallery]
enable = true
[[gallery.gallery_item]]
image = "images/2020-square-2.png"
[[gallery.gallery_item]]
image = "images/2020-square-1.png"
[social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
