author = "Themefisher"
description = "Location de chambres à Paris, avec jardin."
[banner]
heading = "Une maison d'exception avec jardin  à Paris"
image = "images/ferber-front.webp"
[blog]
heading = "Le charme de Paris et le plaisir que donne la campagne.  Proche des moyens de transport ( Bus, Tram, Métro, Vélo, Motolyb etc.)"
[call_to_action]
button_label = "Réservez"
button_url = "contact"
content = "Contactez-nous pour connaitre les disponibilités."
enable = true
title = "Contactez-nous"
[footer]
address = "Paris 20ème, métro Pelleport et porte de Bagnollet."
content = ""
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = ""
title = "About This Site"
[gallery]
enable = false
[[gallery.gallery_item]]
image = "images/2020-square-2.png"
[[gallery.gallery_item]]
image = "images/2020-square-1.png"
[social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
