author = "Themefisher"
description = "This is meta description"
[banner]
heading = "Une maison d'exception avec jardin à Paris"
image = "images/ferber-front.webp"
[blog]
heading = "Le charme de Paris et le plaisir que donne la campagne.  Proche des moyens de transport ( Bus, Tram, Métro, Vélo, Motolyb etc.)"
[call_to_action]
button_label = "Réservez"
button_url = "contact"
content = "Contactez-nous pour connaitre les disponibilités."
enable = true
title = "Contactez-nous"
[footer]
address = "123 Main Street <br> New York, NY 10001"
content = "This may be a good place to introduce yourself and your site or include some credits."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About This Site"
[gallery]
enable = false
[[gallery.gallery_item]]
image = "images/2020-square-2.png"
[[gallery.gallery_item]]
image = "images/2020-square-1.png"
[social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
